### ISSUE TITLE
KC-3D datasets

### ISSUE THREAD

**Issue by TenderPower** [ragavsachdeva/CYWS-3D#5]
Hello author, Very interesting work!  where can I download the KC-3D dataset?

**Comment by ragavsachdeva** [comment]
Hi, I'll try to release it this week. Sorry for the delay.

**Comment by TenderPower** [comment]
Thanks for your quick reply!

**Comment by ragavsachdeva** [comment]
@TenderPower I've added the [datasets](https://github.com/ragavsachdeva/CYWS-3D?tab=readme-ov-file#datasets) and sample dataloaders. Feel free to let me know if you encounter any issues.
