### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory(how to solve this problem)

### ISSUE THREAD

**Issue by gjpblabla** [ragavsachdeva/CYWS-3D#8]
I was trying to run the inference.py file, using the steps you gave me, but it was the same problem many times. When using _wget https://thor.robots.ox.ac.uk/cyws-3d/cyws-3d.ckpt.gz_ download is too slow so I manually go to this website to download him down, and then to extract
![image](https://github.com/user-attachments/assets/9e748d96-cf33-4f3a-a5e5-d6a0168354bc)

**Comment by ragavsachdeva** [comment]
Hi, sorry for the delayed response. I don't actively monitor this repo anymore.

By the looks of it, it seems to be an issue with ZoeDepth model, not the cyws-3d checkpoint? I hope you've solved it as I don't have any actionable advice for you I'm afraid.
